module.exports = function(grunt) {
  'use strict';
  var git = require('git-rev');

  // Project configuration.
  grunt.initConfig({
    meta : {
      fingerprint : null // generated by git-rev
    },
    requirejs : require('./.grunt/requirejs'),
    uglify : {
      build : {
        files : {
          'bundles/patterns.<%= meta.fingerprint %>.min.js' : ['bundles/patterns.<%= meta.fingerprint %>.js']
        }
      },
      standalone : {
        files : {
          'bundles/patterns-standalone.<%= meta.fingerprint %>.min.js' : ['bundles/patterns-standalone.<%= meta.fingerprint %>.js']
        }
      }
    },
    clean : {
      build : [
        'bundles/patterns*.js'
      ]
    },
    symlink : {
      bundles: {
        files : {
          'bundles/patterns-standalone.js'     : 'patterns-standalone.<%= meta.fingerprint %>.js',
          'bundles/patterns-standalone.min.js' : 'patterns-standalone.<%= meta.fingerprint %>.min.js',
          'bundles/patterns.js'                : 'patterns.<%= meta.fingerprint %>.js',
          'bundles/patterns.min.js'            : 'patterns.<%= meta.fingerprint %>.min.js'
        }
      }
    }
  });

  grunt.registerMultiTask('symlink', 'Create symlinks.', function() {
    var fs = require('fs'),
        dest = this.file.dest,
        src = this.file.src[0];
    try{
      fs.symlinkSync(src, dest);
      var rel = dest.substr(0, dest.lastIndexOf('/') + 1);
      grunt.log.ok('created symlink at ' + dest +
                   ' that points to ' + src +
                   ' (relative to ' + rel +')'
      );
    } catch(e){
      if (e.code === 'EEXIST') grunt.log.error(dest + ' already exists, skipping');
    }
  });

  grunt.registerTask('git-rev',function(){
    var done = this.async();
    git.tag(function(string){
      grunt.config('meta.fingerprint', string);
      done();
    })
  });

  grunt.registerTask('check','Run unit tests through PhantomJS',function(){
    var done = this.async();
    runCommand('phantomjs',['lib/phantom-jasmine/lib/run_jasmine_test.coffee','tests/index.html'], done);
  })

  grunt.registerTask('localize-demo-images','Localize Demo Images',function(){
    var done = this.async();
    runCommand('tools/localize-demo-images.sh',[], done);
  })

  grunt.registerTask('doc','Build docs',function(){
    var done = this.async();
    runCommand('sphinx-build',['-b', 'html','docs','build/docs'], done);
  })

  function runCommand(command, args, done) {
    grunt.log.write('Running ' + command + '...');
    grunt.util.spawn({
      cmd: command,
      args: args
    }, function(err, result, code) {
      if (err) grunt.log.error().error(result);
      else     grunt.log.ok().writeln(result);
      done(code);
    });
  }

  grunt.loadNpmTasks('grunt-contrib-requirejs');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-contrib-uglify');

  grunt.registerTask('default', ['git-rev', 'requirejs', 'uglify', 'symlink']);

};

